-- 04 - Calcular a quantidade de alunos, a media da nota e da
-- frequência por código e nome da disciplna.

SELECT DCP.COD_DISC, DCP.NOME_DISC,

COUNT(ALN.COD_MATRICULA) AS QTD_ALUNOS,
FORMAT(AVG(HST.NOTA), 'N2') AS MEDIA_NOTA,
AVG(HST.FREQUENCIA) AS MEDIA_FREQ

FROM TURMA TRM

INNER JOIN ALUNO ALN ON (TRM.COD_MATRICULA = ALN.COD_MATRICULA)
INNER JOIN DISCIPLINA DCP ON (TRM.COD_DISC = DCP.COD_DISC)
INNER JOIN PROFESSOR PRF ON (TRM.COD_PROF = PRF.COD_PROF)
INNER JOIN HISTORICO HST ON (TRM.ANO = HST.ANO AND
TRM.COD_MATRICULA = HST.COD_MATRICULA AND
TRM.COD_DISC = HST.COD_DISC)

GROUP BY DCP.COD_DISC, DCP.NOME_DISC
ORDER BY DCP.COD_DISC, DCP.NOME_DISC;