--01 - Listar a matricula e nome do aluno, codigo e nome da disciplina, codigo e nome do professor, além da frequência e
--nota de cada indivíduo. listado.

SELECT ALN.COD_MATRICULA, ALN.NOME,
DCP.COD_DISC, DCP.NOME_DISC,
PRF.COD_PROF, PRF.NOME,
HST.FREQUENCIA, HST.NOTA

FROM TURMA TRM

INNER JOIN ALUNO ALN ON (TRM.COD_MATRICULA = ALN.COD_MATRICULA)
INNER JOIN DISCIPLINA DCP ON (TRM.COD_DISC = DCP.COD_DISC)
INNER JOIN PROFESSOR PRF ON (TRM.COD_PROF = PRF.COD_PROF)
INNER JOIN HISTORICO HST ON (TRM.ANO = HST.ANO AND
TRM.COD_MATRICULA = HST.COD_MATRICULA AND
TRM.COD_DISC = HST.COD_DISC)

ORDER BY ALN.COD_MATRICULA, ALN.NOME,
DCP.COD_DISC, DCP.NOME_DISC,
PRF.COD_PROF, PRF.NOME,
HST.FREQUENCIA, HST.NOTA;